const data={
    products:[
      {
        Name:'MOOTOU',
        slug:'MOOTOU',
        prix:20000,
        category:'Accéssoires personnels et deco interieur',
        Image:'/Images/pochette.png',
        CountInStock:30,
        brand:'la loincloth',
        rating:4.5,
        numReviews:21,
        description:'high quality',
      } , 
        {
        Name:'SAKI',
        slug:'SAKI',
        prix:5000,
        category:'Women cloth',
        Image:'/Images/short.png',
        CountInStock:78,
        brand:'la loincloth',
        rating:2.5,
        numReviews:28,
        description:'high quality',
      } , 

      {
        
       Name:'MAMA',
       slug:'MAMA',
       prix:50000,
       category:'men cloth',
       Image:'/Images/boubou.png',
       CountInStock:16,
       brand:'la loincloth',
       rating:9.5,
       numReviews:50,
       description:'high quality',  
      },
      
      {
        Name:'DEBOO',
        slug:'DEBOO',
        prix:20000,
        category:'women cloth',
        Image:'/Images/robe.png',
        CountInStock:10,
        brand:'la loincloth',
        rating:3.5,
        numReviews:8,
        description:'high quality',
      } , 
  
      {
        Name:'DIOMGALE',
        slug:'DIOMGALE',
        prix:30000,
        category:'men cloth',
        Image:'/Images/chic.png',
        CountInStock:13,
        brand:'la loincloth',
        rating:8.5,
        numReviews:21,
        description:'high quality',
      } , 
      {
        Name:'YODI',
        slug:'YODI',
        prix:25000,
        category:'Children cloth',
        Image:'/Images/petit.png',
        CountInStock:15,
        brand:'la loincloth',
        rating:4.3,
        numReviews:10,
        description:'high quality',
      },
      {
        Name:'LINGUERE',
        slug:'LINGUERE',
        prix:5000,
        category:'Accéssoires femmes et deco inteieur ',
        Image:'/Images/bracelets.png',
        CountInStock:9,
        brand:'la loincloth',
        rating:6.5,
        numReviews:9,
        description:'high quality',
      } ,
      {
        Name:'FEWNDE',
        slug:'FEWNDE',
        prix:10000,
        category:'Accéssoires personnels et deco interieur',
        Image:'/Images/montre.png',
        CountInStock:17,
        brand:'la loincloth',
        rating:7.5,
        numReviews:21,
        description:'high quality',
      } , 
      {
        Name:'YONTA',
        slug:'YONTA',
        prix:15000,
        category:'children cloth',
        Image:'/Images/large.png',
        CountInStock:30,
        brand:'la loincloth',
        rating:5.5,
        numReviews:30,
        description:'high quality',
      } , 
      {
        Name:'DILLI',
        slug:'DILLI',
        prix:25000,
        category:'women cloth',
        Image:'/Images/chemise.png',
        CountInStock:13,
        brand:'la loincloth',
        rating:1.5,
        numReviews:21,
        description:'high quality',
      } , 
      {
        Name:'HABILLAGES',
        slug:'HABILLAGES',
        prix:15000,
        category:'women cloth',
        Image:'/Images/habillages.png',
        CountInStock:13,
        brand:'la loincloth',
        rating:6.3,
        numReviews:19,
        description:'high quality',
          } , 
            {
        Name:'MANDA',
        slug:'MANDA',
        prix:20000,
        category:'Accéssoires personnels et deco interieur',
        Image:'/Images/pochette.png',
        CountInStock:65,
        brand:'la loincloth',
        rating:6.2,
        numReviews:26,
        description:'high quality',
      } , 
      {
       Name:'TOUBA',
       slug:'TOUBA',
       prix:30000,
       category:'Women cloth',
       Image:'/Images/patalon.png',
       CountInStock:20,
       brand:'la loincloth',
       rating:5.4,
       numReviews:50,
       description:'high quality',
          } , 
          {
      Name:'COLIER',
      slug:'COLIER',
      prix:30000,
      category:'Accéssoires personnels et deco interieur',
      Image:'/Images/boucle.png',
      CountInStock:20,
      brand:'la loincloth',
      rating:5.2,
      numReviews:40,
      description:'high quality',
          } , 
    
      {
      Name:'CHAPEAU',
      slug:'CHAPEAU',
      prix:25000,
      category:'Accéssoires personnels et deco interieur',
      Image:'/Images/chapeauu.png',
      CountInStock:20,
      brand:'la loincloth',
      rating:5.2,
      numReviews:40,
      description:'high quality',
          } , 
     {
      Name:'DIAWDI',
      slug:'DIAWDI',
      prix:40000,
      category:'Accéssoires personnels et deco interieur',
      Image:'/Images/manequin.png',
      CountInStock:20,
      brand:'la loincloth',
      rating:5.2,
      numReviews:40,
      description:'high quality',
          } , 

    ],
};
export default data;
